[송석준] Assignment 3, 4, 5: Express API - CRUD(1)
wecode-bootcamp-korea/44-backend-westagram-1 pull request #20
Opened 2023-03-24 04:16 UTC by songsong95

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-03-24 06:33 UTC, Kang-kyunghun requested changes

2023-03-24 06:33 UTC, Kang-kyunghun commented on song/app.js
> +      res.status(200).json({ data: rows });
- 작성하신 코드에서 DataSource.query()가 비동기적으로 실행되는 함수입니다.
- 비동기 처리를 하는 방법은 크게 callback, promise, async/await를 사용하는 방법이 있는데, 작성하신 코드에서는 이를 혼합해서 사용하고 있습니다. 아래 예제를 참고해서 리펙토링해주세요.
- 전체 코드에 동일하게 수정해주셔야 하는 항목인데 참고 바랍니다!
    
    ```jsx
    // callback 방식의 비동기처리
    app.get("/posts", (req, res) => {
        myDataSource.query(`SELECT * FROM posts`,
          // 비동기 처리 이후에 실행되는 callback
          (err, data) => {res.status(200).json({ data: data })}
        );
    });
    
    // async와 await 방식의 비동기처리
    app.get("/posts", async(req, res) => {
      const posts = await myDataSource.query(`SELECT * FROM posts`);
      
      res.status(200).json({ data : posts})
    });
    
    ```

2023-03-24 07:58 UTC, Kang-kyunghun requested changes

2023-03-24 07:58 UTC, Kang-kyunghun commented on song/app.js
> +});
1. 해당 API 잘 호출 되시나요? {data: rows}에서 rows가 어디에도 정의 되지 않아서 결과가 안 나올 것 같은데, 확인해 주세요.
2. 전체 Post를 호출하는 API 같은데, 이럴 경우에는 FROM을 users가 아닌 posts에서 시작하는 것이 좋습니다.
```suggestion
app.get("/list", async (req, res, next) => {
  const rows = await appDataSource.query(
    `SELECT
          users.id as userId,
          users.profile_image as userProfileImage,
          posts.user_id as postingId,
          posts.image_url as postingImageUrl,
          posts.content as postingContent
        FROM posts
        JOIN users ON posts.user_id = users.id`
  );
  res.status(200).json({ data: rows });
});
```

2023-03-24 07:58 UTC, Kang-kyunghun commented
API 호출결과를 PR template에 첨부해 주세요.

2023-03-24 08:18 UTC, songsong95 commented
file:///home/song137/%EC%82%AC%EC%A7%84/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202023-03-24%2017-15-36.png

2023-03-27 01:51 UTC, songsong95 commented
![스크린샷 2023-03-27 10-40-36](https://user-images.githubusercontent.com/120084509/227822001-54b6af9e-8a82-4c7b-8875-a92e7f966f12.png)

2023-03-27 02:00 UTC, Jon9Beom commented on song/app.js
> +      email,posts
```suggestion
      email,
```
제대로 동작하나요?

2023-03-27 02:00 UTC, Jon9Beom commented on song/db/migrations/20230322025430_create_users_table.sql.sql
> +CREATE TABLE IF NOT EXISTS users (
```suggestion
CREATE TABLE users (
```
`IF NOT EXISTS`는 사용할 필요가 없습니다. 저번에 같이 해결했던건데 또 문제가 생겼나요?

2023-03-27 05:27 UTC, merged