[송석준] Assignment 6, 7, 8: Express API - CRUD(2)
wecode-bootcamp-korea/44-backend-westagram-1 pull request #22
Opened 2023-03-24 13:07 UTC by songsong95

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-03-25 07:02 UTC, Kang-kyunghun requested changes

2023-03-25 07:02 UTC, Kang-kyunghun commented on song/app.js
> +  res.status(201).json({ data: update });
```suggestion
  res.status(200).json({ data: update });
```

2023-03-25 07:02 UTC, Kang-kyunghun commented on song/app.js
> +  // return res status(400).json({message: "key_error"})
해당 코드를 사용하지 않을 거라면 제거해 주세요.

2023-03-25 07:02 UTC, Kang-kyunghun commented on song/app.js
> +            FROM users LEFT JOIN posts ON users.id = posts.user_id`,
게시글 목록을 가져오는 SQL이므로 posts 테이블을 기준으로(FROM posts) 데이터를 가져와 보세요.
```suggestion
            FROM posts 
            JOIN users ON users.id = posts.user_id`,
```

2023-03-27 06:40 UTC, Jon9Beom commented on song/app.js
> +// query 파라미터로 오는 데이터는 모두 string es) const {aa} = req.query
```suggestion
```
- 불필요한 주석은 삭제해주세요!
- 코드에 대한 설명을 주석으로 남겨놓고 싶어서 주석을 달게 되는 것은 처음에는 좋아보일 수는 있으나 나중에 코드에 수정이 발생했을 때 설명하는 주석까지 같이 수정하는 것을 놓치게 된다면 결국 설명 주석과 코드의 내용이 달라지고 오히려 더 유지보수하기 힘들게 될 수 있습니다.
- 주석으로 코드를 설명하기보다는 코드 자체의 가독성이 좋게만들어서 부가적인 설명이 필요없는 코드로 만들어주세요!

2023-03-27 06:40 UTC, Jon9Beom commented on song/app.js
> +    //하나를 호출할 경우
```suggestion
```

2023-03-27 06:40 UTC, Jon9Beom commented on song/app.js
> +  res.status(200).json({ message: "likeCreated" });
```suggestion
  res.status(201).json({ message: "likeCreated" });
```
created라는 응답 메세지에 적합한 상태 코드를 쓰는 것이 적절해보입니다.

2023-03-27 06:40 UTC, Jon9Beom commented on song/app.js
> +app.patch("/update", async (req, res, next) => {
```suggestion
app.patch("/posts", async (req, res) => {
```
1. http method인 `PATCH` 자체가 수정을 의미하기 때문에, 엔드포인트(목적 자원)에 `/update`라고 작성하는 것 보다는, 어떤걸 PATCH 할 지 써주는게 보다 직관적입니다. `/posts`처럼요. 이와 같이 작성하면 http method와 엔드포인트의 조합만으로 무엇을(what), 어떻게(how) 하겠다는 것을 자명하게 나타낼 수 있습니다. 이러한 엔드포인트 설계 아키텍쳐를 REST라고 하는데 이는 금주에 세션에서 자세한 내용과 함께, 다시 한 번 다룰 예정이니 지금은 '그렇구나~' 인지만 하고 넘어가시면 될 것 같습니다. 수정해주세요!
2. 콜백 함수의 세번째 인자로 받는 `next`는 express에서 다음 middleware로 넘기는 next function을 위한 자리인데 지금은 사용하지 않으니 없어도 됩니다.

2023-03-27 06:40 UTC, Jon9Beom commented on song/app.js
> +  res.status(200).json({ data: update });
```suggestion
  return res.status(201).json({ data: update });
```
PATCH라는 method와 API 내부 로직을 생각해본다면 단순 응답을 나타내는 status code인 200보다 적절한 상태코드를 사용할 수 있을 것 같습니다.

2023-03-27 06:40 UTC, Jon9Beom commented on song/app.js
> +});
```suggestion
app.delete("/posts/:postId", async (req, res) => {
  const { postId } = req.params;
  await appDataSource.query(
    `DELETE FROM posts
    WHERE posts.id = ?`, [ postId ]
  );
  
  return res.status(204).send();
});
```
지금 현재 로직으로는 해당 유저가 작성한 게시글을 전부 지우는 건데 의도하신건가요? 
클라이언트에서 요청으로 넘겨받는 하나의 게시글만 삭제 할 수 있도록 수정해주세요.

1. 위에서 언급드린 코멘트와 마찬가지로 엔드포인트에는 `delete`와 같은 동사(동작)가 들어가지 않도록 해주세요. http method 가지고 충분히 설명이 됩니다.
2. delete 메소드에는 body로 데이터를 보내지 않도록, 예시와 같이 params로 혹은 query(추후에 다뤄볼 예정입니다)로 보낼 수 있도록 수정 해주세요. 이는 실제로 delete method를 사용할 때에는 body로 들어오는 데이터를 파싱하지 않도록 설계된 프레임워크나, 버전이 있기 때문에 꼭 사용해야한다면 유의하여 사용하되, 원칙적으로는 지양하는 것이 좋습니다. 의도와 다르게 동작할 수 있습니다.
3. 가급적 불가피 한 경우가 아니라면, 템플릿 리터럴(`${}`)보다 place holder(`?`)를 사용할 수 있도록 해주세요. 이는 보안과 연관 있는데, 이후에 구두로 설명 드리겠습니다.
4. delete method에는 204라는 status code를 응답으로 더 많이 쓰고 있습니다. 다만 204는 message로 no content를 의미하고 실제로 바디에 어떠한 데이터를 담아서 보내지 않으므로 send()만 해주면 됩니다.

2023-03-27 08:41 UTC, Jon9Beom commented on song/app.js
> +    WHERE posts.user_id = ?`,
```suggestion
    WHERE posts.id = ?`,
```
변수를 기존의 userId와 달리 postId를 받도록 수정되었기 때문에 raw sql query도 수정되어야 합니다.

2023-03-27 08:58 UTC, Jon9Beom commented
LGTM 👍

2023-03-27 08:58 UTC, merged